Editorial: register application/manifest+json with IANA
w3c/manifest pull request #985
Opened 2021-06-23 01:30 UTC by marcoscaceres

Closes #970 

This change (choose at least one, delete ones that don't apply):

* Makes editorial changes (changes informative sections, or changes normative sections without changing behavior)

2021-06-23 05:35 UTC, christianliebel requested changes
Very cool! Thanks a lot.

Just a nit: The new name for "MIME type" seems to be "media type," at least the [IANA website](https://www.iana.org/assignments/media-types/media-types.xhtml) states that.

2021-06-23 05:35 UTC, christianliebel commented on index.html
> +        The `application/manifest+json` MIME type
```suggestion
        The `application/manifest+json` media type
```

2021-06-23 05:35 UTC, christianliebel commented on index.html
> +        "application manifest MIME type">application/manifest+json</dfn></code>,
```suggestion
        "application manifest media type">application/manifest+json</dfn></code>,
```

2021-06-23 05:45 UTC, marcoscaceres commented
Good point.. fixing!

2021-06-23 05:51 UTC, christianliebel approved these changes

2021-06-28 09:59 UTC, marcoscaceres commented
Had to add the registration back in. Apparently, we also need to have it in the spec, although redundant.

2021-06-28 10:19 UTC, merged